const config = {
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      "underline",
      "alignment",
      "bulletedList",
      "numberedList",
      "insertTable",
      "|",
      "fontFamily",
      "fontSize",
      "fontColor",
      "fontBackgroundColor",
      "highlight",
      "|",
      "outdent",
      "indent",
      "|",
      "imageUpload",
      "imageInsert",
      "mediaEmbed",
      "link",
      "|",
      "horizontalLine",
      "pageBreak",
      "blockQuote",
      "undo",
      "redo",
      "code",
      "codeBlock",
      "findAndReplace",
      "htmlEmbed",
      "removeFormat",
      "sourceEditing",
      "specialCharacters",
      "restrictedEditingException",
      "strikethrough",
      "style",
      "subscript",
      "superscript",
      "textPartLanguage",
      "todoList",
    ],
    shouldNotGroupWhenFull: true,
  },
  removePlugins: ["Title", "Markdown"],
  mediaEmbed: {
    toolbar: ["mediaEmbed", "undo", "redo"],
  },
  language: "en",
  image: {
    uploadUrl: "http://localhost:8000/api/form-data",
  },
  fontSize: {
    options: [
      9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 44,
      48, 56, 64, 72,
    ],
  },
};
export default config;
